#!/bin/bash

# vim: ts=24:
#   WARNINGS: HARD TABS within; best viewed with a tabstop of "24".  If your
#   editor is vim/compatible, you'll see it like that.

[ -z "$1" ] && {
    cat <<EOF

sf extends the 'fd' command in the following ways:

*   prepends '-HI -L -E .git -E .cache'; looking for files is no time to be
    shy and hold back ;-)

*   -f, -d, -l are short for -t f, -t d, -t l
    *   but if -d is followed by a number, it's maxdepth!
    *   we don't have shortcuts for -t x and -t e

*   -s is short for -S
    *   (I don't think I will ever need case-sensitive matches so no loss)
    *   if the number is not followed by a suffix, add 'b'
    *   'fd' does not seem to allow exact size, it requires a + or a -.  So
        convert "-s 100" to "-S +100b -S -100b".

*   -m is short for --changed-within or --changed-before, depending on sign of argument
    *   if the argument has no suffix, use "m" for min

*   -S and -M have the same semantics as -s and -m, except they pipe to ls -al
    with appropriate flags to sort on the corresponding field

EOF
    exit 1;
}

# tell bash to transfer control to aa, with this script ($0) as the rc file,
# and "sf" being the initial command
export AA_RC=$0
exec ~/bin/__ sf "$@"

exit $?

# the next line is a marker that says the rest of this script is an active
# alias script.  It should always be preceded by an "exit $?" so that in case
# control of the shell script falls through to this point, bash or sh do not
# try to execute the aa script as shell commands!

#!__

# overload "-d" to serve both as max-depth and "-t d"
%% -d (\d+)	%1 --max-depth %2
%% -(d|f|l)	%1 -t %2

# set up the -X command and the pipe for -S and -M
%% -S
    export _SF_PIPE=ls -aUld | sort -k5,5n
    %1 -s
%% -M
    export _SF_PIPE=ls -aUld --time-style=full-iso | sort -k6,7
    %1 -m

# size options: handle exact size (default unit is bytes)
%% -s (\d+)	%1 --size +%2b --size -%2b
%% -s ([-+]\d+)	%1 --size %2b
%% -s ([-+]\d+[bkmgt])	%1 --size %2

# file mod time options: allow a more compact, find-like, syntax (default minutes)
%% -m ([-+]\d+)	%1 -m %2m
%% -m -(\d+.*)	%1 --changed-within %2
%% -m +(\d+.*)	%1 --changed-before %2

sf %%
    ? pl $ENV{_SF_PIPE}
    && sh fd -HI -L -E .git -E .cache %1 -X $_SF_PIPE
    ||    fd -HI -L -E .git -E .cache %1
